package com.example.myhome.model

import com.google.gson.annotations.SerializedName

data class House(
    @SerializedName("markerId") val markerId: String,
    @SerializedName("markerType") val markerType: String,
    @SerializedName("latitude") val latitude: Double,
    @SerializedName("longitude") val longitude: Double,
    @SerializedName("complexName") val complexName: String,
    @SerializedName("realEstateTypeCode") val realEstateTypeCode: String,
    @SerializedName("realEstateTypeName") val realEstateTypeName: String,
    @SerializedName("completionYearMonth") val completionYearMonth: String,
    @SerializedName("totalDongCount") val totalDongCount: Int,
    @SerializedName("totalHouseholdCount") val totalHouseholdCount: Int,
    @SerializedName("floorAreaRatio") val floorAreaRatio: Int,
    @SerializedName("minDealUnitPrice") val minDealUnitPrice: Int,
    @SerializedName("maxDealUnitPrice") val maxDealUnitPrice: Int,
    @SerializedName("minLeaseUnitPrice") val minLeaseUnitPrice: Int,
    @SerializedName("maxLeaseUnitPrice") val maxLeaseUnitPrice: Int,
    @SerializedName("minLeaseRate") val minLeaseRate: Int,
    @SerializedName("maxLeaseRate") val maxLeaseRate: Int,
    @SerializedName("minArea") val minArea: String,
    @SerializedName("maxArea") val maxArea: String,
    @SerializedName("minDealPrice") val minDealPrice: Int,
    @SerializedName("maxDealPrice") val maxDealPrice: Int,
    @SerializedName("minLeasePrice") val minLeasePrice: Int,
    @SerializedName("maxLeasePrice") val maxLeasePrice: Int,
    @SerializedName("minRentPrice") val minRentPrice: Int,
    @SerializedName("maxRentPrice") val maxRentPrice: Int,
    @SerializedName("minShortTermRentPrice") val minShortTermRentPrice: Int,
    @SerializedName("maxShortTermRentPrice") val maxShortTermRentPrice: Int,
    @SerializedName("isDealShown") val isDealShown: Boolean,
    @SerializedName("priceCount") val priceCount: Int,
    @SerializedName("representativeArea") val representativeArea: Double,
    @SerializedName("medianDealUnitPrice") val medianDealUnitPrice: Int,
    @SerializedName("medianDealPrice") val medianDealPrice: Int,
    @SerializedName("isPresales") val isPresales: Boolean,
    @SerializedName("representativePhoto") val representativePhoto: String,
    @SerializedName("photoCount") val photoCount: Int,
    @SerializedName("dealCount") val dealCount: Int,
    @SerializedName("leaseCount") val leaseCount: Int,
    @SerializedName("rentCount") val rentCount: Int,
    @SerializedName("shortTermRentCount") val shortTermRentCount: Int,
    @SerializedName("totalArticleCount") val totalArticleCount: Int,
    @SerializedName("existPriceTab") val existPriceTab: Boolean
)