package com.example.myhome.model

data class SearchParameters(
    val cortarNo: String = "4113511100",
    val zoom: String = "16",
    val priceType: String = "RETAIL",
    val markerId: String = "",
    val markerType: String = "",
    val selectedComplexNo: String = "",
    val selectedComplexBuildingNo: String = "",
    val fakeComplexMarker: String = "",
    val realEstateType: String = "APT:ABYG:JGC:PRE",
    val tradeType: String = "A1",
    var rentPriceMin: String = "0",
    var rentPriceMax: String = "900000000",
    var priceMin: String = "100000",
    var priceMax: String = "120000",
    val areaMin: String = "0",
    var areaMax: String = "900000000",
    val oldBuildYears: String = "",
    val recentlyBuildYears: String = "",
    val minHouseHoldCount: String = "",
    val maxHouseHoldCount: String = "",
    val showArticle: String = "false",
    val sameAddressGroup: String = "false",
    val minMaintenanceCost: String = "",
    val maxMaintenanceCost: String = "",
    val directions: String = "",
    var leftLon: String = "127.0881899",
    var rightLon: String = "127.1242388",
    var topLat: String = "37.3612162",
    var bottomLat: String = "37.347588",
    val isPresale: String = "true"
)

fun SearchParameters.toMap(): Map<String, String> {
    return mapOf(
        "cortarNo" to cortarNo,
        "zoom" to zoom,
        "priceType" to priceType,
        "markerId" to markerId,
        "markerType" to markerType,
        "selectedComplexNo" to selectedComplexNo,
        "selectedComplexBuildingNo" to selectedComplexBuildingNo,
        "fakeComplexMarker" to fakeComplexMarker,
        "realEstateType" to realEstateType,
        "tradeType" to tradeType,
        "rentPriceMin" to rentPriceMin,
        "rentPriceMax" to rentPriceMax,
        "priceMin" to priceMin,
        "priceMax" to priceMax,
        "areaMin" to areaMin,
        "areaMax" to areaMax,
        "oldBuildYears" to oldBuildYears,
        "recentlyBuildYears" to recentlyBuildYears,
        "minHouseHoldCount" to minHouseHoldCount,
        "maxHouseHoldCount" to maxHouseHoldCount,
        "showArticle" to showArticle,
        "sameAddressGroup" to sameAddressGroup,
        "minMaintenanceCost" to minMaintenanceCost,
        "maxMaintenanceCost" to maxMaintenanceCost,
        "directions" to directions,
        "leftLon" to leftLon,
        "rightLon" to rightLon,
        "topLat" to topLat,
        "bottomLat" to bottomLat,
        "isPresale" to isPresale
    )
}